name: Test Pong Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run local Pong Action
        uses: ./
        with:
          winning-score: 1
      - name: Upload SVG
        uses: actions/upload-artifact@v3
        with:
          name: pong-svg
          path: pong_light.svg
