name: Generate Pong SVGs

on:
  workflow_dispatch:

jobs:
  generate-pong-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SVGs
        uses: ./
        with:
          winning-score: 1

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add pong_light.svg pong_dark.svg
          git commit -m "Update Pong SVGs"
          git push
